# Generated by Django 5.0.6 on 2024-07-11 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('clud_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('state_province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.club')),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=30)),
                ('paid_for', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.player')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingKitCollection',
            fields=[
                ('kit_id', models.AutoField(primary_key=True, serialize=False)),
                ('kit_name', models.CharField(max_length=30)),
                ('collection_date', models.DateField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.player')),
            ],
        ),
    ]
